# Buildspec for deploying changes
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
      python: latest
    commands:
      # Need CloudFormation-lint for template check
      - pip install cfn-lint
      # Install dependencies for github-status-update
      - cd src/github-status-update && npm i && cd ../..
      # Install dependencies for github-webhooks
      - cd src/github-webhooks && npm i && cd ../..
  build:
    commands:
      # Template lint check
      - cfn-lint src/template.yaml src/pipeline.yaml
      # Package templates
      - mkdir dist
      - >
        sam package \
          --template-file src/template.yaml \
          --output-template-file dist/template.yaml \
          --s3-bucket $PIPELINE_BUCKET
      - >
        sam package \
          --template-file src/pipeline.yaml \
          --output-template-file dist/pipeline.yaml \
          --s3-bucket $PIPELINE_BUCKET
      # Upload templates
      - aws s3 cp dist s3://$PIPELINE_BUCKET --recursive